# Android Gradle settings (UTF-8 no BOM)
org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
org.gradle.java.home=D:\\build-cache\\jdk-21
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.workers.max=2